---
title: "NYPD Analysis"
output:
  html_document: default
  word_document: default
---
# Q1

```{r, fig.height = 9, fig.width = 16}
require(readr)
require(dplyr)
require(stringr)
require(ggplot2)
npyd.vechicle <- read_csv("NYPD_Motor_Vehicle_Collisions-2.csv", col_names = T)
colnames(npyd.vechicle) <- str_replace_all(colnames(npyd.vechicle), " ", "_")
q1 <- npyd.vechicle %>% 
  mutate(num = 1,
         Num_Injured = NUMBER_OF_PERSONS_INJURED + NUMBER_OF_PEDESTRIANS_INJURED + NUMBER_OF_CYCLIST_INJURED + NUMBER_OF_MOTORIST_INJURED,
         Num_Killed = NUMBER_OF_PERSONS_KILLED + NUMBER_OF_PEDESTRIANS_KILLED + NUMBER_OF_CYCLIST_KILLED + NUMBER_OF_MOTORIST_KILLED
         ) %>%
  filter(!is.na(CROSS_STREET_NAME)) %>%
  group_by(CROSS_STREET_NAME) %>%
  summarise(count = n(), 
            Num_Injured = sum(Num_Injured),
            Num_Killed = sum(Num_Killed)) %>%
  ungroup
require(tidyr)
ggplot(data = q1 %>% arrange(-count) %>% top_n(5,count) %>% 
         gather("count", "Num_Injured", "Num_Killed",
                                                             key = Type, value = Num),
       aes(x = CROSS_STREET_NAME, y =  Num, fill = Type)) +
   geom_col(position = "dodge") +
  ggtitle("The Most Danger intersection in NYC") +
  theme(axis.text.x  = element_text(angle = 45),
        text = element_text(size = 15, face = "bold"))

ggplot(data = q1 %>% arrange(count)  %>% head(5) %>% 
         gather("count", "Num_Injured", "Num_Killed",
                                                             key = Type, value = Num),
       aes(x = CROSS_STREET_NAME, y =  Num, fill = Type)) +
   geom_col(position = "dodge") +
  ggtitle("The Most Safe intersection in NYC") +
  theme(axis.text.x  = element_text(angle = 45),
        text = element_text(size = 15, face = "bold"))
```

# Q2
```{r, fig.height = 9, fig.width = 16}

q2.1 <- npyd.vechicle %>%
  rename(VEHICLE_TYPE_CODE = VEHICLE_TYPE_CODE_1) %>%
  group_by(VEHICLE_TYPE_CODE) %>%
  summarise(count = n()) %>%
  mutate(Type = "VEHICLE_TYPE_CODE_1")
  
q2.2 <- npyd.vechicle %>%
  rename(VEHICLE_TYPE_CODE = VEHICLE_TYPE_CODE_2) %>%
  group_by(VEHICLE_TYPE_CODE) %>%
  summarise(count = n()) %>%
  mutate(Type = "VEHICLE_TYPE_CODE_2")

q2 <- union_all(q2.1, q2.2) %>%
  filter(!VEHICLE_TYPE_CODE %in% c("UNKNOWN", "OTHER", NA)) %>%
  group_by(Type) %>%
  arrange(-count) %>%
  top_n(10,count)

ggplot(data = q2,
       aes(x = VEHICLE_TYPE_CODE, y =  count, fill = Type)) +
   geom_col(position = "stack") +
  ggtitle("The top 10 of vehicles most frequently caused a collision") +
  theme(axis.text.x  = element_text(angle = 45),
        text = element_text(size = 15, face = "bold"))

```

# Q3
```{r, fig.height = 9, fig.width = 16}

q3.1 <- npyd.vechicle %>%
  rename(CONTRIBUTING_FACTOR_VEHICLE = CONTRIBUTING_FACTOR_VEHICLE_1) %>%
  group_by(CONTRIBUTING_FACTOR_VEHICLE) %>%
  summarise(count = n()) %>%
  mutate(Type = "CONTRIBUTING_FACTOR_VEHICLE_1")
  
q3.2 <- npyd.vechicle %>%
  rename(CONTRIBUTING_FACTOR_VEHICLE = CONTRIBUTING_FACTOR_VEHICLE_2) %>%
  group_by(CONTRIBUTING_FACTOR_VEHICLE) %>%
  summarise(count = n()) %>%
  mutate(Type = "CONTRIBUTING_FACTOR_VEHICLE_2")

q3 <- union_all(q3.1, q3.2) %>%
  filter(!CONTRIBUTING_FACTOR_VEHICLE %in% c("UNKNOWN", "Unspecified", NA)) %>%
  group_by(Type) %>%
  arrange(-count) %>%
  top_n(10,count)

ggplot(data = q3,
       aes(x = CONTRIBUTING_FACTOR_VEHICLE, y =  count, fill = Type)) +
   geom_col(position = "stack") +
  ggtitle("The top 10 of popular contributing factors that led to a collision") +
  theme(axis.text.x  = element_text(angle = 45),
        text = element_text(size = 15, face = "bold"))
```

# Q4
```{r, fig.height = 9, fig.width = 16}

q4 <- npyd.vechicle %>%
  mutate(Injureed_or_Killed = NUMBER_OF_PERSONS_INJURED + NUMBER_OF_PEDESTRIANS_INJURED + NUMBER_OF_CYCLIST_INJURED + NUMBER_OF_MOTORIST_INJURED +NUMBER_OF_PERSONS_KILLED + NUMBER_OF_PEDESTRIANS_KILLED + NUMBER_OF_CYCLIST_KILLED + NUMBER_OF_MOTORIST_KILLED
  ) %>%
  mutate(Injureed_or_Killed_Yes = ifelse(Injureed_or_Killed > 0, 1, 0))

prop <- mean(q4$Injureed_or_Killed_Yes)
knitr::kable(data.frame(prop),
             caption = "The probability that people were injured or killed from the collision")
  
```

# Q5
```{r, fig.height = 9, fig.width = 16}
# 30 minute
require(lubridate)
q5.1 <- npyd.vechicle %>%
  group_by(TIME) %>%
  summarise(n = n()) %>%
  mutate(time = hms(TIME),
         time = hour(time)*3600 + minute(time)*60 + second(time),
         times = ceiling(time/1800),
         time.end = time/1800
         )

q5.interval <- q5.1 %>%
  filter(times == time.end) %>%
  union_all(q5.1 %>% top_n(1)) %>%
  select(times, TIME)

q5.interval <- q5.interval %>%
  rename(begin.time = TIME) %>%
  inner_join(
    q5.interval %>%
      rename(end.time = TIME) %>%
  mutate(times = times - 1) 
  )


q5.2 <- q5.1 %>%
  group_by(times) %>%
  summarise(n = sum(n)) %>%
  inner_join(q5.interval) %>%
  arrange(-n) %>% 
  mutate(happn.times = n) %>%
  select(begin.time, end.time, happn.times) %>%
  mutate(time.interval = paste0(begin.time, "->", end.time)) %>%
  arrange(begin.time)

ggplot(data = q5.2,
       aes(x = time.interval, y =  happn.times, fill = time.interval)) +
   geom_col(position = "stack") +
  ggtitle("The Carsh Happen in Time Period") +
    theme(axis.text.x  = element_text(angle = 45),
        text = element_text(size = 15, face = "bold"),
        legend.position="none")
```

